# https://docs.npmjs.com/cli/configuring-npm/package-json
version: 0.1.0
name: postcss-import-glob
description: PostCSS plugin to inline CSS @imports, with support for glob patterns.
keywords:
- plugin
- css
- postcss
- postcss-plugin
- import
- "@import"
- glob
- glob-pattern
- styles
- stylesheets

homepage: https://npm.im/postcss-import-glob
repository: danielbayley/postcss-import-glob
bugs: https://github.com/danielbayley/postcss-import-glob/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: danielbayley.dev

funding: https://github.com/danielbayley/postcss-import-glob?sponsor=1
license: MIT

type: module
imports:
  "#utils": &utils ./lib/utils.js
  "#test": ./lib/test.js
exports: &index ./index.js
files:
- *index
- *utils
publishConfig:
  access: public

engines:
  node: &node-version ">=22"
  pnpm: &pnpm-version ">=10"
devEngines:
  runtime:
    name: node
    version: *node-version
  packageManager:
  - name: pnpm
    version: *pnpm-version
  - name: npm
packageManager: pnpm@10.32.1

peerDependencies: &peerDependencies
  postcss: ^8.5.8

devDependencies:
  <<: *peerDependencies
  knip: ^5.86.0
  publint: ^0.3.18
  yaml: ^2.8.2

scripts:
  prepare: yaml --single --merge --json --indent ${TABSIZE:-2} < package.yaml > package.json

  test: node --test --experimental-test-coverage test/*.js

  prerelease: git stash --include-untracked --keep-index && pnpm prepare
  release: pnpm version --force --no-git-tag-version
  postrelease: pnpm publish

  prepublishOnly: publint
  postpublish: git stash pop --quiet

  version: >-
    sed -i "" -E "s/^(version: *)$npm_old_version\$/\\1$npm_new_version/" package.yaml &&
    git commit --message  $npm_new_version package.yaml &&
    git tag    --annotate $npm_new_version --message v$npm_new_version &&
    git push   --follow-tags

  watch: pnpm test --watch
  clean: git clean -X --force
  zap: pnpm clean && rm -rf node_modules || true
  reinstall: pnpm zap && pnpm install
